### ISSUE TITLE
Unable to pip install 0.20.2

### ISSUE THREAD

**Issue by tkch3n** [feast-dev/feast#2660]
## Expected Behavior 
Install `feast==0.20.2` without errors.

## Current Behavior
When I try to install `feast==0.20.2` with `pip`, I'm getting the following error:

```
Collecting feast[aws,redis,snowflake]==0.20.2
  Using cached feast-0.20.2.tar.gz (295 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-ub_hk5b9/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 177, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "/tmp/pip-build-env-ub_hk5b9/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 159, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-ub_hk5b9/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 281, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/tmp/pip-build-env-ub_hk5b9/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 174, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 176, in <module>
          with open(README_FILE, "r", encoding="utf8") as f:
      FileNotFoundError: [Errno 2] No such file or directory: '/tmp/README.md'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
``` 

## Steps to reproduce
```bash
pip install feast==0.20.2
```
### Specifications

- Version: `0.20.2`
- Platform: Docker (`python:3.9-slim`)
- Subsystem:

**Comment by tkch3n** [comment]
I'm thinking this has to do with my M1 mac since I can install it fine on a EC2 instance. But I was able to install `0.20.0` just fine on M1. So I wondered what changed.

**Comment by kevjumba** [comment]
Hello @tkch3n, this is a known issue that will be fixed in the next minor release coming soon. Wheels on m1 aren't being built properly in pypi.

**Comment by achals** [comment]
I think this is related to #2639, and fixed by #2630. We should close this when we release version 0.21 (hopefully tomorrow or the day after).

**Comment by jonathanmiao** [comment]
I am still seeing this problem since 0.21.0. Actually it happens for every release even for the latest 0.28.0. Does anyone know how to fix it?
