### ISSUE TITLE
UI - Error Loading Project Configs

### ISSUE THREAD

**Issue by ngoduykhanh** [feast-dev/feast#4981]
I've searched for similar issues opened previously here, but didn't see any useful information so I'd like to open a new one.

## Expected Behavior 

The UI loads successfully

## Current Behavior

The UI is accessible but can't load anything

<img width="1299" alt="Image" src="https://github.com/user-attachments/assets/760281ab-aca0-4c46-8593-fe7812dc0b94" />

## Steps to reproduce

I have tried both local setup using the Quickstart guide and deploying to Kubernetes. They have the same issue.

I enabled the DEBUG log of Feast UI container and saw no error.

If I log in into the feast-ui container, I can run feast cli successfully without issue.

```
(app-root) bash-5.1$ feast feature-views list
/opt/app-root/lib64/python3.11/site-packages/feast/feature_view.py:48: DeprecationWarning: Entity value_type will be mandatory in the next release. Please specify a value_type for entity '__dummy'.
  DUMMY_ENTITY = Entity(
Received base64 encoded feature_store.yaml
NAME                         ENTITIES    TYPE
driver_hourly_stats_fresh    {'driver'}  FeatureView
driver_hourly_stats          {'driver'}  FeatureView
transformed_conv_rate_fresh  {'driver'}  OnDemandFeatureView
transformed_conv_rate        {'driver'}  OnDemandFeatureView
```

### Specifications

- Version: 0.43
- Platform: MacOS/Kubernetes
- Subsystem:

**Comment by itsmano1993** [comment]
I am facing the same issue

**Comment by redhatHameed** [comment]
limited knowledge on UI part, but I believe [this](https://github.com/feast-dev/feast/pull/4772/files) PR should fix that. However, it's not part of the `0.43.0` current version.

**Comment by tchughesiv** [comment]
@redhatHameed it doesn't appear to resolve the issue... i just ran the latest code w/ -
```bash
make -C infra/feast-operator install deploy IMG=quay.io/feastdev-ci/feast-operator:develop FS_IMG=quay.io/feastdev-ci/feature-server:develop
kubectl apply -f infra/feast-operator/config/samples/v1alpha1_featurestore_all_services_default.yaml
```

**Comment by redhatHameed** [comment]
@tchughesiv thanks for verifying, can you make sure that while loading the page you  see the [PR](https://github.com/feast-dev/feast/pull/4772/files) code changes.

**Comment by danbaron63** [comment]
Same issue installing and running feast==0.43.0 using `uv`.

**Comment by hark444** [comment]
I'm facing the same issue. I'm getting this error on the UI:
_Error loading project configs. There was an error loading the Project Configurations. Please check that feature_store.yaml file is available and well-formed._

**Comment by franciscojavierarceo** [comment]
@nanohanno any idea on this one?

**Comment by tchughesiv** [comment]
this has been resolved and can be tested w/ the latest operator & feature-server image development builds -
```bash
# from the latest master branch, against a kubernetes cluster
$ git checkout 0145e5501e2c7854628d204cb515270fac3bee7d
$ make -C infra/feast-operator install deploy IMG=quay.io/feastdev-ci/feast-operator:$(git rev-parse HEAD) FS_IMG=quay.io/feastdev-ci/feature-server:$(git rev-parse HEAD)
$ kubectl apply -f infra/feast-operator/config/samples/v1alpha1_featurestore_all_services_default.yaml
$ kubectl wait --for=condition=available --timeout=8m deploy/feast-sample-all-services
$ kubectl exec deploy/feast-sample-all-services -c registry -- feast apply
```
from an openshift cluster, a route will be exposed that you can use to access to UI.
from a kubernetes cluster, the following can be done to quickly test the UI -
```bash
$ kubectl port-forward svc/feast-sample-all-services-ui 8080:80
```
in k8s, after the port-forward, access - http://localhost:8080/

**Comment by ngoduykhanh** [comment]
Nice! Thanks @tchughesiv for the quick fix. Looking forward to seeing the official release.
